### ISSUE TITLE
You can make `length` be a property

### ISSUE THREAD

**Issue by cuixiping** [jerry1100/electron-browser-storage#1]
You can make `length` be a property

```
Object.defineProperty(this, "length", {
  get : function(){
    return execute(`window.${storageName}.length;`);
  }
);
```

**Comment by jerry1100** [comment]
Neat idea. However, I think having an asynchronous `length` property might be confusing. I can see users making the mistake of thinking it's synchronous because it's not a function.

IOW I think `localStorage.length()` is more indicative of it being asynchronous than `localStorage.length`, which people may wrongly assume to be synchronous.

**Comment by cuixiping** [comment]
I agree with you.
Electron saves localStorage and cookie in sqlite. Is it possible to read content from sqlite directly?

**Comment by jerry1100** [comment]
@cuixiping I feel like it should be possible, but I'd have to find some time to look into it.

Feel free to look into it in the meantime 🙂.

**Comment by jerry1100** [comment]
It's been a while so I'm going to close this.
